### ISSUE TITLE
Add a checkout example to the Usage section in the README

### ISSUE THREAD

**Issue by litan1106** [jenkinsci/pipeline-as-yaml-plugin#17]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please add a checkout example to the Usage section in the README.md

**Comment by aytuncbeken** [comment]
Hi Thanks for the issue. 

Could you please provide more details ? Checkout as a step or something else ?

**Comment by litan1106** [comment]
Yes, I was trying to convert my existing pipeline from groovy to yaml. (the checkout didn't look so good with my example in yaml.)

```yaml
pipeline:
  agent:
    node:
      label: "docker"
  triggers:
    - cron('H */4 * * 1-5')
  stages:
    - stage: "Checkout"
      steps:
        script:
          - "checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'example-cred', url: 'git@github.com:example/helloworld.git']]])"
```
