### ISSUE TITLE
stash and unstash

### ISSUE THREAD

**Issue by royalsoulmates** [jenkinsci/pipeline-as-yaml-plugin#33]
Can you please provide examples for stash and unstash usage examples? I tried below, but looks likes not way to declare.

      agent:
        label: "Master"
      steps:
        - deleteDir()
        - unstash 'ucdPackage'
        - echo '1'

**Comment by aytuncbeken** [comment]
Hi @royalsoulmates ,

You can find the example below.
```
pipeline:
  agent:
    label: 'master'
  stages:
    - stage: "Create"
      steps:
        script:
          - sh "touch test.txt"
    - stage: "Stash"
      steps:
        - "stash allowEmpty: true, excludes: 'excludes', includes: '*.*', name: 'name'"
    - stage: "Unstash"
      steps:
        - "cleanWs()"
        - "unstash 'name'"
```
