### ISSUE TITLE
Add support for Kubernetes plugin

### ISSUE THREAD

**Issue by ferrucciobongianni** [jenkinsci/pipeline-as-yaml-plugin#37]
Hi,
It would be great if we could use pipeline-as-yaml-plugin to describe a pipeline which uses the kubernetes agent. At the moment it doesn't seem to be possible.
Something like:

```
pipeline:
  agent:
    kubernetes:
      cloud: mystack
      yaml: >
        apiVersion: v1
        kind: Pod
        spec:
            imagePullSecrets:
            - name: my-creds
            containers:
            - name: ubuntu
              image: myimage:1.1
              command: ['sleep', 'infinity']
              tty: true
              imagePullPolicy: Always'''
    stages:
      - stage: Test
        steps: echo "Hello world"
```

I've tried to run the pipeline above through the _conversion tool_ provided by the plugin and it _almost_ worked. The problem is that they "yaml" key's value gets converted in a string with single quotes, which doesn't work with multiline strings such as the pod definition above.
I reckon if the plugin was able to wrap the value of the `yaml` key in a multiline string (e.g. '''string''') that would work
