### ISSUE TITLE
Parity with standard Jenkinsfile for Docker

### ISSUE THREAD

**Issue by m0un10** [jenkinsci/pipeline-as-yaml-plugin#42]
**Is your feature request related to a problem? Please describe.**

Since the standard Jenkinsfile doesn't require an explicit clone, pipeline as yaml shouldn't either. 

**Describe the solution you'd like**

When it is yaml from SCM it should automatically have the code cloned (as per the configuration) to be consistent with what happens for Jenkinsfile from SCM.

**Describe alternatives you've considered**

The workaround is to add an explicit checkout

This works..
```
pipeline {
    agent { 
        docker { 
            image 'maven:3.3.3' 
            reuseNode true
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
```
But this doesn't
```
pipeline:
  agent:
    docker:
      image: maven:3.3.3
      # 2. Reusing the node (double-check that this doesn't happen automatically)
      reuseNode: 'true'
  stages:
    - stage: "build"
      steps:
        - sh "mvn clean package"
```

Unless you add a clone step before the maven build
```
        - "checkout([$class: 'GitSCM', branches: [[name: '*/jenkins-poc']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'example-cred', url: 'https://github.com/example-org/example-repo.git']]])"
 ```
